services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: "http://localhost:5001"
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5001:5000"
    env_file:
      - .env
